//===-- gala/format.h -----------------------------------*- mode: C++11 -*-===//
//
//                              _____     _
//                             |   __|___| |___
//                             |  |  | .'| | .'|
//                             |_____|__,|_|__,|
//
//       This file is distributed under the terms described in LICENSE.
//
//===----------------------------------------------------------------------===//
///
/// \file
/// \brief
///
//===----------------------------------------------------------------------===//

#ifndef _GALA_FORMAT_H_
#define _GALA_FORMAT_H_

#include "gala/foundation.h"

GALA_BEGIN_EXTERN_C

/// \def GALA_FORMAT_SIGNED
/// \brief Signed format.
#define GALA_FORMAT_SIGNED (0 << 31)

/// \def GALA_FORMAT_UNSIGNED
/// \brief Unsigned format.
#define GALA_FORMAT_UNSIGNED (1 << 31)

/// \def GALA_FORMAT_INTEGER
/// \brief Unsigned format.
#define GALA_FORMAT_INTEGER (0 << 30)

/// \def GALA_FORMAT_FLOAT
/// \brief Floating-point.
#define GALA_FORMAT_FLOAT (1 << 30)

/// \def GALA_FORMAT_NORMALIZED
/// \brief Integer normalized to floating point.
#define GALA_FORMAT_NORMALIZED (1 << 29)

/// \brief
///
typedef enum gala_format {
  /// Invalid.
  GALA_FORMAT_INVALID = 0,

  GALA_FORMAT_X_S8      = 1 | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XY_S8     = 2 | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZ_S8    = 3 | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZW_S8   = 4 | GALA_FORMAT_INTEGER,

  GALA_FORMAT_X_U8      = 5 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XY_U8     = 6 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZ_U8    = 7 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZW_U8   = 8 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,

  GALA_FORMAT_X_N8      = GALA_FORMAT_X_S8    | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XY_N8     = GALA_FORMAT_XY_S8   | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZ_N8    = GALA_FORMAT_XYZ_S8  | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZW_N8   = GALA_FORMAT_XYZW_S8 | GALA_FORMAT_NORMALIZED,

  GALA_FORMAT_X_UN8     = GALA_FORMAT_X_U8    | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XY_UN8    = GALA_FORMAT_XY_U8   | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZ_UN8   = GALA_FORMAT_XYZ_U8  | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZW_UN8  = GALA_FORMAT_XYZW_U8 | GALA_FORMAT_NORMALIZED,

  GALA_FORMAT_X_S16     =  9 | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XY_S16    = 10 | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZ_S16   = 11 | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZW_S16  = 12 | GALA_FORMAT_INTEGER,

  GALA_FORMAT_X_U16     = 13 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XY_U16    = 14 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZ_U16   = 15 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZW_U16  = 16 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,

  GALA_FORMAT_X_N16     = GALA_FORMAT_X_S16    | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XY_N16    = GALA_FORMAT_XY_S16   | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZ_N16   = GALA_FORMAT_XYZ_S16  | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZW_N16  = GALA_FORMAT_XYZW_S16 | GALA_FORMAT_NORMALIZED,

  GALA_FORMAT_X_UN16    = GALA_FORMAT_X_U16    | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XY_UN16   = GALA_FORMAT_XY_U16   | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZ_UN16  = GALA_FORMAT_XYZ_U16  | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZW_UN16 = GALA_FORMAT_XYZW_U16 | GALA_FORMAT_NORMALIZED,

  GALA_FORMAT_X_S32     = 17 | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XY_S32    = 18 | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZ_S32   = 19 | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZW_S32  = 20 | GALA_FORMAT_INTEGER,

  GALA_FORMAT_X_U32     = 21 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XY_U32    = 22 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZ_U32   = 23 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,
  GALA_FORMAT_XYZW_U32  = 24 | GALA_FORMAT_UNSIGNED | GALA_FORMAT_INTEGER,

  GALA_FORMAT_X_N32     = GALA_FORMAT_X_S32    | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XY_N32    = GALA_FORMAT_XY_S32   | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZ_N32   = GALA_FORMAT_XYZ_S32  | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZW_N32  = GALA_FORMAT_XYZW_S32 | GALA_FORMAT_NORMALIZED,

  GALA_FORMAT_X_UN32    = GALA_FORMAT_X_U32    | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XY_UN32   = GALA_FORMAT_XY_U32   | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZ_UN32  = GALA_FORMAT_XYZ_U32  | GALA_FORMAT_NORMALIZED,
  GALA_FORMAT_XYZW_UN32 = GALA_FORMAT_XYZW_U32 | GALA_FORMAT_NORMALIZED,

  GALA_FORMAT_X_F16     = 25 | GALA_FORMAT_FLOAT,
  GALA_FORMAT_XY_F16    = 26 | GALA_FORMAT_FLOAT,
  GALA_FORMAT_XYZ_F16   = 27 | GALA_FORMAT_FLOAT,
  GALA_FORMAT_XYZW_F16  = 28 | GALA_FORMAT_FLOAT,

  GALA_FORMAT_X_F32     = 29 | GALA_FORMAT_FLOAT,
  GALA_FORMAT_XY_F32    = 30 | GALA_FORMAT_FLOAT,
  GALA_FORMAT_XYZ_F32   = 31 | GALA_FORMAT_FLOAT,
  GALA_FORMAT_XYZW_F32  = 32 | GALA_FORMAT_FLOAT,

  /// \internal Force gala_uint32_t storage and alignment.
  GALA_FORMAT_TYPE_FORCE_UINT32 = 0x7fffffff
} gala_format_t;

GALA_END_EXTERN_C

#endif // _GALA_FORMAT_H_




